In [8]:
import json
import numpy as np

def process_annotations(input_file, output_file):
    """
    Process an annotation JSON file to output bounding boxes in x, y, w, h format.

    Parameters:
    - input_file (str): Path to the input annotation JSON file.
    - output_file (str): Path to save the processed JSON file.
    """
    # Load the original JSON file
    with open(input_file, 'r') as file:
        data = json.load(file)

    # Initialize lists for ground truth and predictions
    gt_boxes = []
    pred_boxes = []

    # Process ground truth and predictions
    for annotation in data["imagesLib"][0]["annotations"]:
        # Get the class name
        class_name = data["classes"][annotation["classI"]]["name"]
        
        # Extract bounding box in x, y, w, h format
        x = annotation["position"]["x"]
        y = annotation["position"]["y"]
        w = annotation["position"]["width"]
        h = annotation["position"]["height"]
        box = [x, y, w, h]
        
        # Separate ground truth and predictions based on the class name
        if class_name == "Truth":
            gt_boxes.append(box)
        elif class_name == "Pred":
            pred_boxes.append(box)

    # Convert lists to numpy arrays
    gt_boxes_np = np.array(gt_boxes)
    pred_boxes_np = np.array(pred_boxes)

    # Generate ground truth labels (all ones)
    gt_labels_np = np.ones(len(gt_boxes_np), dtype=int)

    # Generate predicted labels (all ones) and random scores
    pred_labels_np = np.ones(len(pred_boxes_np), dtype=int)
    pred_scores_np = np.random.uniform(0, 1, size=len(pred_boxes_np))

    # Create the output structure
    output_data = {
        "gt_boxes": gt_boxes_np.tolist(),
        "gt_labels": gt_labels_np.tolist(),
        "pred_boxes": pred_boxes_np.tolist(),
        "pred_labels": pred_labels_np.tolist(),
        "pred_scores": pred_scores_np.tolist()
    }

    # Save the processed data to a new JSON file
    with open(output_file, 'w') as file:
        json.dump(output_data, file, indent=4)

    print(f"Processed JSON saved to {output_file}")

# Example usage
input_file = "./pictures/annotations.json"  # Replace with the path to your input file
output_file = "./pictures/stick_peds.json"  # Replace with the desired output file path
process_annotations(input_file, output_file)


Processed JSON saved to ./pictures/stick_peds.json


In [7]:
import json
import numpy as np

def load_annotations(json_file):
    """
    Load annotations from a JSON file and return values as numpy arrays.

    Parameters:
    json_file (str): Path to the annotations JSON file.

    Returns:
    tuple: Numpy arrays for gt_boxes, gt_labels, pred_boxes, pred_labels, pred_scores.
    """
    # Load the JSON file
    with open(json_file, 'r') as file:
        data = json.load(file)
    
    # Convert the JSON lists to numpy arrays
    gt_boxes = np.array(data["gt_boxes"])
    gt_labels = np.array(data["gt_labels"])
    pred_boxes = np.array(data["pred_boxes"])
    pred_labels = np.array(data["pred_labels"])
    pred_scores = np.array(data["pred_scores"])
    
    return gt_boxes, gt_labels, pred_boxes, pred_labels, pred_scores

gt_boxes, gt_labels, pred_boxes, pred_labels, pred_scores = load_annotations("./pictures/stick_peds.json")


In [6]:
# Load the annotations from the JSON file
gt_boxes, gt_labels, pred_boxes, pred_labels, pred_scores = load_annotations("./pictures/processed_annotations.json")

# Print the arrays
print("Ground Truth Boxes:\n", gt_boxes)
print("Ground Truth Labels:\n", gt_labels)
print("Predicted Boxes:\n", pred_boxes)
print("Predicted Labels:\n", pred_labels)
print("Predicted Scores:\n", pred_scores)


Ground Truth Boxes:
 [[170.35074627  97.34328358 251.47014925 235.24626866]
 [377.20522388  73.00746269 454.26865672 200.77052239]
 [547.55597015 168.32276119 615.49347015 273.77798507]
 [748.32649254  60.83955224 810.18003731 175.42070896]
 [908.53731343 165.28078358 985.60074627 295.07182836]
 [867.97761194 416.75093284 933.88712687 523.22014925]
 [717.90671642 283.91791045 794.97014925 412.69496269]
 [488.74440299 386.33115672 567.8358209  511.05223881]
 [265.66604478 335.6299774  340.70149254 454.26710426]
 [ 75.03544776 306.22574627 136.88899254 405.59701493]]
Ground Truth Labels:
 [1 1 1 1 1 1 1 1 1 1]
Predicted Boxes:
 [[179.4766791  102.41324627 256.54011194 242.34421642]
 [366.05130597  82.13339552 442.10074627 210.91044776]
 [519.1641791  149.05690299 600.28358209 239.30223881]
 [492.80037313  31.43376866 552.62593284 112.55317164]
 [145.00093284 159.19682836 235.24626866 225.10634328]
 [121.67910448 440.07276119 181.50466418 517.13619403]
 [ 79.09141791 307.23973881 134.8610